#!/usr/bin/env bash
# while loop to print Holberton School 10 times but on 9th iteration print hi instead

i=0
while ((i < 10))
do
    if ((i == 3))
    then
        echo "bad luck"
    elif ((i == 7))
    then
	echo "good luck"
    else
        echo "Holberton School"
    fi
    i=$(( i + 1 ))
done
