#!/usr/bin/env bash
# while loop to print Holberton School 10 times but on 9th iteration print hi instead

i=1
while ((i < 21))
do
    if ((i == 4))
    then
        echo "$i"
        echo "bad luck from China"
    elif ((i == 9))
    then
	echo "$i"
        echo "bad luck from Japan"
    elif ((i == 17))
    then
	echo "$i"
	echo "bad luck from Italy"
    else
        echo "$i"
    fi
    i=$(( i + 1 ))
done
