#!/usr/bin/env bash
# While loop to print 1-20 and says if the number is bad luck

i=1
while ((i < 21))
do
    echo "$i"
    case $i in
        4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    i=$(( i + 1 ))
done
