#!/usr/bin/env bash
# While loop to mimic clock first 12 hours and 59 minutes

i=0
j=1
while ((i <= 12))
do
    echo "Hour: $i"
    if ((i < 12))
    then
        while ((j <= 59))
        do
	    echo "$j"
	    j=$(( j + 1 ))
        done
    fi
    j=0
    i=$(( i + 1 ))
done
